<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Exercise;
use App\Models\MuscleGroup;
use Illuminate\Support\Str;

class ExerciseLibrarySeeder extends Seeder
{
    public function run(): void
    {
        // Get all muscle groups to map IDs
        $muscleGroups = MuscleGroup::all()->pluck('id', 'name');

        $exercises = [
            // PECHO
            [
                'name' => 'Press de Banca con Barra',
                'muscleGroup' => 'Pecho',
                'equipment' => 'Barra y banco plano',
                'description' => 'Acostado en un banco plano, agarra la barra a una anchura ligeramente mayor que los hombros. Baja la barra controladamente hasta el pecho y empuja hacia arriba hasta extender los brazos.',
                'primaryMuscles' => ['Pectoral mayor'],
                'secondaryMuscles' => ['Tríceps', 'Deltoides anterior'],
                'benefits' => ['Desarrolla fuerza y masa en el pecho', 'Mejora la capacidad de empuje horizontal', 'Ejercicio compuesto con alta activación muscular'],
                'level' => 'Principiante',
            ],
            [
                'name' => 'Press Inclinado con Mancuernas',
                'muscleGroup' => 'Pecho',
                'equipment' => 'Mancuernas y banco inclinado',
                'description' => 'En banco inclinado a 30-45°, sostén una mancuerna en cada mano a la altura del pecho. Empuja hacia arriba juntando ligeramente las mancuernas en la parte alta del movimiento.',
                'primaryMuscles' => ['Pectoral mayor (porción clavicular)'],
                'secondaryMuscles' => ['Deltoides anterior', 'Tríceps'],
                'benefits' => ['Énfasis en la parte superior del pecho', 'Mayor rango de movimiento que con barra', 'Corrige desequilibrios entre ambos lados'],
                'level' => 'Principiante',
            ],
            [
                'name' => 'Aperturas con Mancuernas',
                'muscleGroup' => 'Pecho',
                'equipment' => 'Mancuernas y banco plano',
                'description' => 'Acostado en banco plano con mancuernas arriba, baja los brazos abiertos con codos ligeramente flexionados describiendo un arco amplio. Regresa a la posición inicial apretando el pecho.',
                'primaryMuscles' => ['Pectoral mayor'],
                'secondaryMuscles' => ['Deltoides anterior', 'Bíceps (estabilización)'],
                'benefits' => ['Excelente estiramiento del pectoral', 'Aislamiento del pecho sin intervención del tríceps', 'Mejora la conexión mente-músculo'],
                'level' => 'Principiante',
            ],
            [
                'name' => 'Fondos en Paralelas (Pecho)',
                'muscleGroup' => 'Pecho',
                'equipment' => 'Barras paralelas',
                'description' => 'Sujétate en las barras paralelas con los codos rectos. Inclina el torso hacia adelante y baja flexionando los codos hasta que los hombros queden por debajo de los codos. Empuja hacia arriba.',
                'primaryMuscles' => ['Pectoral mayor (porción inferior)'],
                'secondaryMuscles' => ['Tríceps', 'Deltoides anterior'],
                'benefits' => ['Gran activación de la parte baja del pecho', 'Fortalece tríceps simultáneamente', 'Ejercicio funcional con el peso corporal'],
                'level' => 'Intermedio',
            ],
            [
                'name' => 'Press de Banca Declinado',
                'muscleGroup' => 'Pecho',
                'equipment' => 'Barra y banco declinado',
                'description' => 'En un banco con inclinación negativa, baja la barra hasta la parte inferior del pecho. Empuja controladamente hasta extender los brazos manteniendo los omóplatos retraídos.',
                'primaryMuscles' => ['Pectoral mayor (porción esternal)'],
                'secondaryMuscles' => ['Tríceps', 'Deltoides anterior'],
                'benefits' => ['Enfoca la porción inferior del pecho', 'Menor estrés en los hombros que el press plano', 'Permite manejar cargas pesadas'],
                'level' => 'Intermedio',
            ],
            [
                'name' => 'Crossover en Polea',
                'muscleGroup' => 'Pecho',
                'equipment' => 'Poleas altas',
                'description' => 'De pie entre dos poleas altas, agarra las manijas y da un paso adelante. Con los brazos ligeramente flexionados, junta las manos al frente a la altura del pecho con un movimiento de abrazo.',
                'primaryMuscles' => ['Pectoral mayor'],
                'secondaryMuscles' => ['Deltoides anterior', 'Serrato anterior'],
                'benefits' => ['Tensión constante durante todo el rango', 'Excelente para definición y contracción pico', 'Versatilidad para variar el ángulo'],
                'level' => 'Principiante',
            ],
            [
                'name' => 'Flexiones de Pecho',
                'muscleGroup' => 'Pecho',
                'equipment' => 'Peso corporal',
                'description' => 'En posición de plancha con las manos ligeramente más anchas que los hombros, baja el cuerpo flexionando los codos hasta que el pecho casi toque el suelo. Empuja de vuelta a la posición inicial.',
                'primaryMuscles' => ['Pectoral mayor'],
                'secondaryMuscles' => ['Tríceps', 'Deltoides anterior', 'Core'],
                'benefits' => ['No requiere equipamiento', 'Se puede hacer en cualquier lugar', 'Fortalece el core como estabilizador'],
                'level' => 'Principiante',
            ],
            [
                'name' => 'Press con Mancuernas en Banco Plano',
                'muscleGroup' => 'Pecho',
                'equipment' => 'Mancuernas y banco plano',
                'description' => 'Acostado en banco plano, sostén las mancuernas sobre el pecho con brazos extendidos. Baja las mancuernas hasta que los codos formen 90° y empuja hacia arriba apretando el pecho.',
                'primaryMuscles' => ['Pectoral mayor'],
                'secondaryMuscles' => ['Tríceps', 'Deltoides anterior'],
                'benefits' => ['Mayor rango de movimiento que con barra', 'Trabaja cada lado independientemente', 'Menor riesgo de lesión en hombros'],
                'level' => 'Principiante',
            ],
            [
                'name' => 'Pullover con Mancuerna',
                'muscleGroup' => 'Pecho',
                'equipment' => 'Mancuerna y banco plano',
                'description' => 'Acostado transversalmente en el banco, sostén una mancuerna con ambas manos sobre el pecho. Baja la mancuerna por detrás de la cabeza con los brazos ligeramente flexionados y regresa.',
                'primaryMuscles' => ['Pectoral mayor', 'Serrato anterior'],
                'secondaryMuscles' => ['Dorsal ancho', 'Tríceps'],
                'benefits' => ['Expande la caja torácica', 'Trabaja pecho y espalda simultáneamente', 'Mejora la movilidad de hombros'],
                'level' => 'Intermedio',
            ],
            [
                'name' => 'Aperturas en Polea Baja',
                'muscleGroup' => 'Pecho',
                'equipment' => 'Poleas bajas',
                'description' => 'De pie entre dos poleas bajas, agarra las manijas y junta las manos al frente a la altura del pecho con un movimiento ascendente. Controla la bajada.',
                'primaryMuscles' => ['Pectoral mayor (porción clavicular)'],
                'secondaryMuscles' => ['Deltoides anterior'],
                'benefits' => ['Enfoca la parte superior del pecho', 'Tensión constante por la polea', 'Ideal para finalizar entrenamientos de pecho'],
                'level' => 'Principiante',
            ],

            // ESPALDA
            [
                'name' => 'Dominadas',
                'muscleGroup' => 'Espalda',
                'equipment' => 'Barra de dominadas',
                'description' => 'Cuelga de una barra con agarre prono (palmas al frente) y anchura mayor que los hombros. Tira del cuerpo hacia arriba hasta que la barbilla supere la barra. Baja controladamente.',
                'primaryMuscles' => ['Dorsal ancho', 'Redondo mayor'],
                'secondaryMuscles' => ['Bíceps', 'Romboides', 'Trapecio inferior'],
                'benefits' => ['Ejercicio rey para la espalda', 'Desarrollo de fuerza funcional de tracción', 'Construye una espalda ancha en forma de V'],
                'level' => 'Intermedio',
            ],
            [
                'name' => 'Remo con Barra',
                'muscleGroup' => 'Espalda',
                'equipment' => 'Barra',
                'description' => 'Con las rodillas ligeramente flexionadas y el torso inclinado a 45°, tira de la barra hacia el abdomen inferior. Aprieta los omóplatos al final del movimiento y baja controladamente.',
                'primaryMuscles' => ['Dorsal ancho', 'Romboides'],
                'secondaryMuscles' => ['Bíceps', 'Trapecio', 'Erector espinal'],
                'benefits' => ['Desarrolla grosor en la espalda media', 'Fortalece la cadena posterior', 'Mejora la postura'],
                'level' => 'Principiante',
            ],
            [
                'name' => 'Jalón al Pecho',
                'muscleGroup' => 'Espalda',
                'equipment' => 'Polea alta con barra lat',
                'description' => 'Sentado en la máquina de jalón, agarra la barra ancha y tira hacia el pecho superior. Mantén el torso ligeramente inclinado hacia atrás y aprieta los dorsales al bajar.',
                'primaryMuscles' => ['Dorsal ancho'],
                'secondaryMuscles' => ['Bíceps', 'Redondo mayor', 'Romboides'],
                'benefits' => ['Alternativa accesible a las dominadas', 'Permite ajustar la carga fácilmente', 'Desarrolla amplitud de la espalda'],
                'level' => 'Principiante',
            ],
            [
                'name' => 'Remo con Mancuerna a Una Mano',
                'muscleGroup' => 'Espalda',
                'equipment' => 'Mancuerna y banco',
                'description' => 'Apoya una rodilla y una mano en el banco. Con la otra mano, tira de la mancuerna hacia la cadera manteniendo el codo pegado al cuerpo. Baja controladamente.',
                'primaryMuscles' => ['Dorsal ancho', 'Romboides'],
                'secondaryMuscles' => ['Bíceps', 'Trapecio medio', 'Infraespinoso'],
                'benefits' => ['Corrige desequilibrios musculares entre lados', 'Gran rango de movimiento', 'Permite enfocar la contracción unilateral'],
                'level' => 'Principiante',
            ],
            [
                'name' => 'Peso Muerto Convencional',
                'muscleGroup' => 'Espalda',
                'equipment' => 'Barra',
                'description' => 'Con los pies al ancho de la cadera, agarra la barra con agarre mixto o doble prono. Levanta la barra extendiendo caderas y rodillas simultáneamente, manteniendo la espalda neutra.',
                'primaryMuscles' => ['Erector espinal', 'Glúteo mayor', 'Isquiotibiales'],
                'secondaryMuscles' => ['Dorsal ancho', 'Trapecio', 'Cuádriceps', 'Core'],
                'benefits' => ['Ejercicio más completo para fuerza total', 'Desarrolla toda la cadena posterior', 'Aumenta fuerza de agarre'],
                'level' => 'Intermedio',
            ],
            [
                'name' => 'Remo en Máquina T',
                'muscleGroup' => 'Espalda',
                'equipment' => 'Máquina T-Bar',
                'description' => 'Parado sobre la plataforma, con el torso inclinado, agarra las manijas y tira del peso hacia el torso. Aprieta los omóplatos en la parte alta y baja lentamente.',
                'primaryMuscles' => ['Dorsal ancho', 'Romboides', 'Trapecio medio'],
                'secondaryMuscles' => ['Bíceps', 'Erector espinal'],
                'benefits' => ['Desarrolla grosor en la espalda', 'Agarre neutro reduce estrés en muñecas', 'Movimiento guiado y seguro'],
                'level' => 'Principiante',
            ],
            [
                'name' => 'Face Pull',
                'muscleGroup' => 'Espalda',
                'equipment' => 'Polea alta con cuerda',
                'description' => 'Con la polea a la altura de la cara, agarra la cuerda y tira hacia la cara separando los extremos. Rota externamente los hombros al final del movimiento.',
                'primaryMuscles' => ['Deltoides posterior', 'Trapecio medio'],
                'secondaryMuscles' => ['Romboides', 'Infraespinoso'],
                'benefits' => ['Previene lesiones de hombro', 'Mejora la postura', 'Equilibra el exceso de trabajo de empuje'],
                'level' => 'Principiante',
            ],
            [
                'name' => 'Remo en Polea Baja',
                'muscleGroup' => 'Espalda',
                'equipment' => 'Polea baja con manija en V',
                'description' => 'Sentado frente a la polea baja, con pies apoyados, tira de la manija hacia el abdomen manteniendo el torso erguido. Extiende los brazos lentamente en la fase negativa.',
                'primaryMuscles' => ['Dorsal ancho', 'Romboides'],
                'secondaryMuscles' => ['Bíceps', 'Trapecio', 'Erector espinal'],
                'benefits' => ['Excelente para grosor de la espalda media', 'Movimiento controlado y seguro', 'Variedad de agarres posibles'],
                'level' => 'Principiante',
            ],
            [
                'name' => 'Jalón con Agarre Cerrado',
                'muscleGroup' => 'Espalda',
                'equipment' => 'Polea alta con manija en V',
                'description' => 'Sentado en la máquina de jalón, usa una manija en V con agarre neutro cerrado. Tira hacia el pecho inclinándote ligeramente hacia atrás. Controla la subida.',
                'primaryMuscles' => ['Dorsal ancho'],
                'secondaryMuscles' => ['Bíceps', 'Romboides', 'Braquial'],
                'benefits' => ['Mayor participación del bíceps', 'Desarrolla los dorsales inferiores', 'Agarre confortable'],
                'level' => 'Principiante',
            ],
            [
                'name' => 'Hiperextensiones',
                'muscleGroup' => 'Espalda',
                'equipment' => 'Banco de hiperextensiones',
                'description' => 'Colócate en el banco de hiperextensiones con la cadera apoyada. Baja el torso controladamente y sube contrayendo los erectores espinales y glúteos. Evita hiperextender.',
                'primaryMuscles' => ['Erector espinal'],
                'secondaryMuscles' => ['Glúteo mayor', 'Isquiotibiales'],
                'benefits' => ['Fortalece la espalda baja', 'Previene dolor lumbar', 'Mejora la estabilidad del core posterior'],
                'level' => 'Principiante',
            ],

            // PIERNAS
            [
                'name' => 'Sentadilla con Barra',
                'muscleGroup' => 'Cuádriceps',
                'equipment' => 'Barra y rack',
                'description' => 'Con la barra apoyada en los trapecios, baja flexionando rodillas y caderas hasta que los muslos queden paralelos al suelo o más abajo. Empuja con los talones para subir.',
                'primaryMuscles' => ['Cuádriceps', 'Glúteo mayor'],
                'secondaryMuscles' => ['Isquiotibiales', 'Erector espinal', 'Core'],
                'benefits' => ['Rey de los ejercicios de pierna', 'Aumenta la producción de testosterona', 'Desarrolla fuerza funcional completa'],
                'level' => 'Principiante',
            ],
            [
                'name' => 'Prensa de Piernas',
                'muscleGroup' => 'Cuádriceps',
                'equipment' => 'Máquina de prensa',
                'description' => 'Sentado en la máquina de prensa con los pies al ancho de los hombros, baja la plataforma flexionando las rodillas a 90°. Empuja la plataforma sin bloquear completamente las rodillas.',
                'primaryMuscles' => ['Cuádriceps', 'Glúteo mayor'],
                'secondaryMuscles' => ['Isquiotibiales', 'Aductores'],
                'benefits' => ['Permite manejar cargas elevadas de forma segura', 'Menor estrés en la espalda baja', 'Ideal para volumen de entrenamiento'],
                'level' => 'Principiante',
            ],
            [
                'name' => 'Peso Muerto Rumano',
                'muscleGroup' => 'Isquios',
                'equipment' => 'Barra',
                'description' => 'De pie con la barra, baja el peso empujando la cadera hacia atrás con las rodillas ligeramente flexionadas. Siente el estiramiento en los isquiotibiales y sube contrayendo glúteos.',
                'primaryMuscles' => ['Isquiotibiales', 'Glúteo mayor'],
                'secondaryMuscles' => ['Erector espinal', 'Aductores'],
                'benefits' => ['Mejor ejercicio para isquiotibiales', 'Desarrolla la cadena posterior', 'Previene lesiones de rodilla'],
                'level' => 'Principiante',
            ],
            [
                'name' => 'Zancadas con Mancuernas',
                'muscleGroup' => 'Cuádriceps',
                'equipment' => 'Mancuernas',
                'description' => 'Con una mancuerna en cada mano, da un paso largo hacia adelante y baja hasta que ambas rodillas formen 90°. Empuja con el pie delantero para volver a la posición inicial.',
                'primaryMuscles' => ['Cuádriceps', 'Glúteo mayor'],
                'secondaryMuscles' => ['Isquiotibiales', 'Aductores', 'Core'],
                'benefits' => ['Mejora el equilibrio y la coordinación', 'Trabajo unilateral que corrige desbalances', 'Gran ejercicio funcional'],
                'level' => 'Principiante',
            ],
            [
                'name' => 'Extensión de Cuádriceps',
                'muscleGroup' => 'Cuádriceps',
                'equipment' => 'Máquina de extensiones',
                'description' => 'Sentado en la máquina, coloca los tobillos detrás del rodillo. Extiende las rodillas hasta que las piernas queden rectas. Baja controladamente sin dejar caer el peso.',
                'primaryMuscles' => ['Cuádriceps'],
                'secondaryMuscles' => [],
                'benefits' => ['Aislamiento puro del cuádriceps', 'Ideal para precalentar las rodillas', 'Excelente conexión mente-músculo'],
                'level' => 'Principiante',
            ],
            [
                'name' => 'Curl Femoral Acostado',
                'muscleGroup' => 'Isquios',
                'equipment' => 'Máquina de curl femoral',
                'description' => 'Acostado boca abajo en la máquina, coloca los tobillos bajo el rodillo. Flexiona las rodillas llevando los talones hacia los glúteos. Baja lentamente.',
                'primaryMuscles' => ['Isquiotibiales'],
                'secondaryMuscles' => ['Gemelos'],
                'benefits' => ['Aislamiento de los isquiotibiales', 'Prevención de lesiones en rodilla y muslo posterior', 'Equilibra la fuerza cuádriceps/isquios'],
                'level' => 'Principiante',
            ],
            [
                'name' => 'Hip Thrust',
                'muscleGroup' => 'Glúteos',
                'equipment' => 'Barra y banco',
                'description' => 'Con la espalda alta apoyada en un banco y la barra sobre la cadera, empuja la cadera hacia arriba apretando los glúteos en la parte alta. Baja controladamente.',
                'primaryMuscles' => ['Glúteo mayor'],
                'secondaryMuscles' => ['Isquiotibiales', 'Cuádriceps', 'Core'],
                'benefits' => ['Mejor ejercicio para activación de glúteos', 'Mejora la potencia en sprint y salto', 'Reduce el dolor de espalda baja'],
                'level' => 'Principiante',
            ],
            [
                'name' => 'Sentadilla Búlgara',
                'muscleGroup' => 'Cuádriceps',
                'equipment' => 'Mancuernas y banco',
                'description' => 'Con un pie apoyado en un banco detrás de ti y una mancuerna en cada mano, baja la rodilla trasera hacia el suelo flexionando la pierna delantera. Sube empujando con el pie delantero.',
                'primaryMuscles' => ['Cuádriceps', 'Glúteo mayor'],
                'secondaryMuscles' => ['Isquiotibiales', 'Aductores', 'Core'],
                'benefits' => ['Excelente para corregir desbalances unilaterales', 'Alta activación de glúteos', 'Mejora la estabilidad de rodilla'],
                'level' => 'Intermedio',
            ],
            [
                'name' => 'Elevación de Gemelos de Pie',
                'muscleGroup' => 'Isquios',
                'equipment' => 'Máquina de gemelos o step',
                'description' => 'De pie con las puntas de los pies en el borde de un step o máquina, sube elevándote sobre las puntas lo más alto posible. Baja lentamente estirando los gemelos.',
                'primaryMuscles' => ['Gastrocnemio'],
                'secondaryMuscles' => ['Sóleo'],
                'benefits' => ['Desarrolla los gemelos', 'Mejora la estabilidad del tobillo', 'Importante para rendimiento deportivo'],
                'level' => 'Principiante',
            ],
            [
                'name' => 'Sentadilla Goblet',
                'muscleGroup' => 'Cuádriceps',
                'equipment' => 'Mancuerna o kettlebell',
                'description' => 'Sostén una mancuerna o kettlebell pegada al pecho con ambas manos. Baja en sentadilla profunda manteniendo el torso erguido y los codos entre las rodillas.',
                'primaryMuscles' => ['Cuádriceps', 'Glúteo mayor'],
                'secondaryMuscles' => ['Core', 'Aductores'],
                'benefits' => ['Excelente para aprender la técnica de sentadilla', 'Mejora la movilidad de caderas', 'Ideal para principiantes'],
                'level' => 'Principiante',
            ],
            [
                'name' => 'Aductores en Máquina',
                'muscleGroup' => 'Cuádriceps',
                'equipment' => 'Máquina de aductores',
                'description' => 'Sentado en la máquina con las piernas abiertas, cierra las piernas apretando los aductores. Abre lentamente controlando el peso.',
                'primaryMuscles' => ['Aductores'],
                'secondaryMuscles' => ['Pectíneo', 'Grácil'],
                'benefits' => ['Fortalece los aductores de la cadera', 'Previene lesiones en la ingle', 'Mejora la estabilidad lateral'],
                'level' => 'Principiante',
            ],
            [
                'name' => 'Step-Up con Mancuernas',
                'muscleGroup' => 'Cuádriceps',
                'equipment' => 'Mancuernas y cajón',
                'description' => 'Con una mancuerna en cada mano, sube a un cajón con un pie empujando desde el talón. Sube completamente y baja con la pierna contraria. Alterna.',
                'primaryMuscles' => ['Cuádriceps', 'Glúteo mayor'],
                'secondaryMuscles' => ['Isquiotibiales', 'Core'],
                'benefits' => ['Ejercicio funcional unilateral', 'Mejora el equilibrio y coordinación', 'Transferencia directa a actividades deportivas'],
                'level' => 'Principiante',
            ],

            // HOMBROS
            [
                'name' => 'Press Militar con Barra',
                'muscleGroup' => 'Hombros',
                'equipment' => 'Barra',
                'description' => 'De pie, con la barra a la altura de los hombros y agarre ligeramente más ancho que los hombros, empuja la barra hacia arriba hasta extender los brazos completamente. Baja controladamente.',
                'primaryMuscles' => ['Deltoides anterior', 'Deltoides medio'],
                'secondaryMuscles' => ['Tríceps', 'Trapecio', 'Core'],
                'benefits' => ['Ejercicio compuesto principal para hombros', 'Desarrolla fuerza de empuje vertical', 'Involucra el core como estabilizador'],
                'level' => 'Principiante',
            ],
            [
                'name' => 'Elevaciones Laterales',
                'muscleGroup' => 'Hombros',
                'equipment' => 'Mancuernas',
                'description' => 'De pie con una mancuerna en cada mano a los lados, eleva los brazos lateralmente hasta la altura de los hombros con los codos ligeramente flexionados. Baja controladamente.',
                'primaryMuscles' => ['Deltoides medio'],
                'secondaryMuscles' => ['Trapecio', 'Supraespinoso'],
                'benefits' => ['Aislamiento del deltoides lateral', 'Crea la apariencia de hombros anchos', 'Mejora la estética de la silueta'],
                'level' => 'Principiante',
            ],
            [
                'name' => 'Pájaros con Mancuernas',
                'muscleGroup' => 'Hombros',
                'equipment' => 'Mancuernas',
                'description' => 'Inclinado hacia adelante con el torso casi paralelo al suelo, eleva las mancuernas lateralmente con los codos ligeramente flexionados. Aprieta los omóplatos arriba.',
                'primaryMuscles' => ['Deltoides posterior'],
                'secondaryMuscles' => ['Romboides', 'Trapecio medio'],
                'benefits' => ['Desarrollo del deltoides posterior (frecuentemente olvidado)', 'Mejora la postura', 'Equilibra el desarrollo del hombro'],
                'level' => 'Principiante',
            ],
            [
                'name' => 'Elevaciones Frontales',
                'muscleGroup' => 'Hombros',
                'equipment' => 'Mancuernas',
                'description' => 'De pie con mancuernas al frente de los muslos, eleva un brazo al frente hasta la altura del hombro con el codo ligeramente flexionado. Baja y alterna.',
                'primaryMuscles' => ['Deltoides anterior'],
                'secondaryMuscles' => ['Pectoral mayor (porción clavicular)', 'Trapecio'],
                'benefits' => ['Aislamiento del deltoides frontal', 'Complementa el press de hombros', 'Fácil de ejecutar con técnica correcta'],
                'level' => 'Principiante',
            ],
            [
                'name' => 'Press con Mancuernas Sentado',
                'muscleGroup' => 'Hombros',
                'equipment' => 'Mancuernas y banco con respaldo',
                'description' => 'Sentado con respaldo a 90°, sostén las mancuernas a la altura de los hombros. Empuja hacia arriba hasta extender los brazos y baja controladamente.',
                'primaryMuscles' => ['Deltoides anterior', 'Deltoides medio'],
                'secondaryMuscles' => ['Tríceps', 'Trapecio'],
                'benefits' => ['Mayor estabilidad que de pie', 'Trabaja cada lado independientemente', 'Menor estrés en la espalda baja'],
                'level' => 'Principiante',
            ],
            [
                'name' => 'Remo al Mentón',
                'muscleGroup' => 'Hombros',
                'equipment' => 'Barra o mancuernas',
                'description' => 'De pie, agarra la barra con agarre cerrado. Tira hacia arriba llevando los codos por encima de los hombros. Baja controladamente.',
                'primaryMuscles' => ['Deltoides medio', 'Trapecio'],
                'secondaryMuscles' => ['Deltoides anterior', 'Bíceps'],
                'benefits' => ['Ejercicio compuesto para hombros y trapecios', 'Desarrolla la línea del hombro', 'Versátil con diferentes agarres'],
                'level' => 'Intermedio',
            ],
            [
                'name' => 'Encogimientos de Hombros',
                'muscleGroup' => 'Hombros',
                'equipment' => 'Barra o mancuernas',
                'description' => 'De pie con peso en las manos y brazos extendidos a los lados, eleva los hombros hacia las orejas apretando los trapecios. Mantén arriba 1-2 segundos y baja.',
                'primaryMuscles' => ['Trapecio superior'],
                'secondaryMuscles' => ['Elevador de la escápula'],
                'benefits' => ['Aislamiento del trapecio superior', 'Mejora la estabilidad del cuello y hombros', 'Simple y efectivo'],
                'level' => 'Principiante',
            ],

            // BÍCEP / TRÍCEP (BRAZOS)
            [
                'name' => 'Curl de Bíceps con Barra',
                'muscleGroup' => 'Bícep',
                'equipment' => 'Barra recta o EZ',
                'description' => 'De pie con la barra con agarre supino (palmas arriba), flexiona los codos llevando la barra hacia los hombros. Mantén los codos pegados al cuerpo. Baja controladamente.',
                'primaryMuscles' => ['Bíceps braquial'],
                'secondaryMuscles' => ['Braquial', 'Braquiorradial'],
                'benefits' => ['Ejercicio clásico para desarrollo de bíceps', 'Permite usar cargas significativas', 'Trabajas ambos brazos simultáneamente'],
                'level' => 'Principiante',
            ],
            [
                'name' => 'Curl Martillo con Mancuernas',
                'muscleGroup' => 'Bícep',
                'equipment' => 'Mancuernas',
                'description' => 'De pie con las mancuernas a los lados y agarre neutro (pulgares arriba), flexiona los codos elevando las mancuernas. Mantén los codos fijos.',
                'primaryMuscles' => ['Braquial', 'Braquiorradial'],
                'secondaryMuscles' => ['Bíceps braquial'],
                'benefits' => ['Desarrolla el braquial para brazos más gruesos', 'Fortalece los antebrazos', 'Posición natural de la muñeca'],
                'level' => 'Principiante',
            ],
            [
                'name' => 'Press Francés con Barra EZ',
                'muscleGroup' => 'Trícep',
                'equipment' => 'Barra EZ y banco plano',
                'description' => 'Acostado en banco plano, sostén la barra EZ con brazos extendidos verticalmente. Flexiona los codos bajando la barra hacia la frente. Extiende los codos para volver arriba.',
                'primaryMuscles' => ['Tríceps (cabeza larga)'],
                'secondaryMuscles' => ['Tríceps (cabeza lateral)', 'Anconeo'],
                'benefits' => ['Excelente aislamiento del tríceps', 'Énfasis en la cabeza larga del tríceps', 'Desarrolla masa en la parte posterior del brazo'],
                'level' => 'Intermedio',
            ],
            [
                'name' => 'Extensión de Tríceps en Polea',
                'muscleGroup' => 'Trícep',
                'equipment' => 'Polea alta con barra o cuerda',
                'description' => 'De pie frente a la polea alta, agarra la barra o cuerda. Con los codos pegados al cuerpo, extiende los brazos hacia abajo. Regresa controladamente sin mover los codos.',
                'primaryMuscles' => ['Tríceps'],
                'secondaryMuscles' => ['Anconeo'],
                'benefits' => ['Tensión constante por la polea', 'Fácil de ajustar la carga', 'Ideal para principiantes y series de acabado'],
                'level' => 'Principiante',
            ],
            [
                'name' => 'Curl Concentrado',
                'muscleGroup' => 'Bícep',
                'equipment' => 'Mancuerna',
                'description' => 'Sentado con las piernas abiertas, apoya el codo en el interior del muslo. Flexiona el codo llevando la mancuerna hacia el hombro con un movimiento estricto.',
                'primaryMuscles' => ['Bíceps braquial'],
                'secondaryMuscles' => ['Braquial'],
                'benefits' => ['Máximo aislamiento del bíceps', 'Elimina la posibilidad de trampa', 'Excelente para el pico del bíceps'],
                'level' => 'Principiante',
            ],
            [
                'name' => 'Fondos en Banco (Tríceps)',
                'muscleGroup' => 'Trícep',
                'equipment' => 'Banco',
                'description' => 'Con las manos apoyadas en el borde del banco detrás de ti y los pies al frente, baja el cuerpo flexionando los codos. Empuja hacia arriba extendiendo los brazos.',
                'primaryMuscles' => ['Tríceps'],
                'secondaryMuscles' => ['Deltoides anterior', 'Pectoral mayor'],
                'benefits' => ['No requiere equipamiento especial', 'Se puede hacer con peso corporal', 'Eficaz para tríceps y estabilización'],
                'level' => 'Principiante',
            ],
            [
                'name' => 'Curl Inclinado con Mancuernas',
                'muscleGroup' => 'Bícep',
                'equipment' => 'Mancuernas y banco inclinado',
                'description' => 'Sentado en banco inclinado a 45°, deja colgar los brazos con mancuernas. Flexiona los codos subiendo las mancuernas. El ángulo permite un mayor estiramiento del bíceps.',
                'primaryMuscles' => ['Bíceps braquial (cabeza larga)'],
                'secondaryMuscles' => ['Braquial'],
                'benefits' => ['Mayor estiramiento del bíceps por el ángulo', 'Enfatiza la cabeza larga del bíceps', 'Previene trampas con impulso'],
                'level' => 'Principiante',
            ],
            [
                'name' => 'Extensión de Tríceps Overhead',
                'muscleGroup' => 'Trícep',
                'equipment' => 'Mancuerna',
                'description' => 'De pie o sentado, sostén una mancuerna con ambas manos detrás de la cabeza. Extiende los codos elevando la mancuerna sobre la cabeza. Baja controladamente.',
                'primaryMuscles' => ['Tríceps (cabeza larga)'],
                'secondaryMuscles' => ['Tríceps (cabeza medial)', 'Anconeo'],
                'benefits' => ['Gran estiramiento de la cabeza larga del tríceps', 'Trabaja el tríceps en posición elongada', 'Se puede hacer con una o dos manos'],
                'level' => 'Principiante',
            ],
            [
                'name' => 'Curl de Bíceps en Polea',
                'muscleGroup' => 'Bícep',
                'equipment' => 'Polea baja con barra',
                'description' => 'De pie frente a la polea baja, agarra la barra con agarre supino y flexiona los codos elevando la barra hacia los hombros. Mantén los codos fijos.',
                'primaryMuscles' => ['Bíceps braquial'],
                'secondaryMuscles' => ['Braquial', 'Braquiorradial'],
                'benefits' => ['Tensión constante a lo largo del movimiento', 'Menor estrés articular', 'Excelente para series de alto volumen'],
                'level' => 'Principiante',
            ],
            [
                'name' => 'Curl de Muñeca (Antebrazos)',
                'muscleGroup' => 'Bícep',
                'equipment' => 'Barra o mancuernas',
                'description' => 'Sentado con los antebrazos apoyados en los muslos y las muñecas colgando, flexiona las muñecas elevando el peso. Baja lentamente para estirar los flexores.',
                'primaryMuscles' => ['Flexores del antebrazo'],
                'secondaryMuscles' => ['Extensores del antebrazo (estabilización)'],
                'benefits' => ['Fortalece el agarre', 'Previene lesiones de muñeca', 'Importante para ejercicios compuestos pesados'],
                'level' => 'Principiante',
            ],

            // CORE
            [
                'name' => 'Plancha Frontal',
                'muscleGroup' => 'Core',
                'equipment' => 'Peso corporal',
                'description' => 'En posición de plancha sobre los antebrazos y las puntas de los pies, mantén el cuerpo en línea recta desde la cabeza hasta los talones. Aprieta el abdomen y glúteos.',
                'primaryMuscles' => ['Recto abdominal', 'Transverso abdominal'],
                'secondaryMuscles' => ['Oblicuos', 'Erector espinal', 'Deltoides'],
                'benefits' => ['Fortalece todo el core isométricamente', 'Mejora la estabilidad de la columna', 'No requiere equipamiento'],
                'level' => 'Principiante',
            ],
            [
                'name' => 'Crunch Abdominal',
                'muscleGroup' => 'Core',
                'equipment' => 'Peso corporal',
                'description' => 'Acostado boca arriba con las rodillas flexionadas, eleva los hombros del suelo contrayendo el abdomen. No tires del cuello. Baja controladamente.',
                'primaryMuscles' => ['Recto abdominal'],
                'secondaryMuscles' => ['Oblicuos'],
                'benefits' => ['Aislamiento efectivo del recto abdominal', 'Fácil de ejecutar y progresar', 'Múltiples variantes disponibles'],
                'level' => 'Principiante',
            ],
            [
                'name' => 'Elevación de Piernas Colgado',
                'muscleGroup' => 'Core',
                'equipment' => 'Barra de dominadas',
                'description' => 'Colgado de una barra de dominadas con los brazos extendidos, eleva las piernas rectas hasta formar un ángulo de 90°. Baja controladamente sin balancear.',
                'primaryMuscles' => ['Recto abdominal (inferior)', 'Flexores de cadera'],
                'secondaryMuscles' => ['Oblicuos', 'Antebrazos (agarre)'],
                'benefits' => ['Excelente para la zona abdominal inferior', 'Fortalece el agarre', 'Ejercicio avanzado de alto rendimiento'],
                'level' => 'Intermedio',
            ],
            [
                'name' => 'Rueda Abdominal',
                'muscleGroup' => 'Core',
                'equipment' => 'Rueda abdominal',
                'description' => 'Arrodillado, agarra la rueda abdominal y rueda hacia adelante estirando el cuerpo lo más que puedas manteniendo el core tenso. Regresa a la posición inicial contrayendo el abdomen.',
                'primaryMuscles' => ['Recto abdominal', 'Transverso abdominal'],
                'secondaryMuscles' => ['Dorsal ancho', 'Deltoides', 'Erector espinal'],
                'benefits' => ['Uno de los ejercicios de core más desafiantes', 'Trabaja el core en extensión completa', 'Fortalece la estabilidad anti-extensión'],
                'level' => 'Intermedio',
            ],
            [
                'name' => 'Russian Twist',
                'muscleGroup' => 'Core',
                'equipment' => 'Peso corporal o mancuerna',
                'description' => 'Sentado con las rodillas flexionadas y el torso inclinado hacia atrás, gira el torso de lado a lado tocando el suelo con las manos o peso a cada lado.',
                'primaryMuscles' => ['Oblicuos'],
                'secondaryMuscles' => ['Recto abdominal', 'Flexores de cadera'],
                'benefits' => ['Trabaja la rotación del core', 'Fortalece los oblicuos', 'Mejora la estabilidad rotacional deportiva'],
                'level' => 'Principiante',
            ],
            [
                'name' => 'Mountain Climbers',
                'muscleGroup' => 'Core',
                'equipment' => 'Peso corporal',
                'description' => 'En posición de plancha alta, lleva alternadamente las rodillas hacia el pecho con un movimiento rápido y controlado. Mantén la cadera baja y el core activado.',
                'primaryMuscles' => ['Recto abdominal', 'Flexores de cadera'],
                'secondaryMuscles' => ['Deltoides', 'Cuádriceps', 'Oblicuos'],
                'benefits' => ['Combina trabajo de core con cardio', 'Eleva la frecuencia cardíaca rápidamente', 'Mejora la coordinación'],
                'level' => 'Principiante',
            ],
            [
                'name' => 'Plancha Lateral',
                'muscleGroup' => 'Core',
                'equipment' => 'Peso corporal',
                'description' => 'Acostado de lado, apóyate sobre el antebrazo y el pie inferior. Eleva la cadera para formar una línea recta. Mantén la posición contrayendo los oblicuos.',
                'primaryMuscles' => ['Oblicuos'],
                'secondaryMuscles' => ['Transverso abdominal', 'Glúteo medio', 'Deltoides'],
                'benefits' => ['Fortalece los estabilizadores laterales del core', 'Mejora el equilibrio lateral', 'Previene el dolor de espalda baja'],
                'level' => 'Principiante',
            ],
            [
                'name' => 'Dead Bug',
                'muscleGroup' => 'Core',
                'equipment' => 'Peso corporal',
                'description' => 'Acostado boca arriba, levanta brazos y piernas (rodillas a 90°). Extiende el brazo derecho y la pierna izquierda simultáneamente sin despegar la espalda baja del suelo. Alterna.',
                'primaryMuscles' => ['Recto abdominal', 'Transverso abdominal'],
                'secondaryMuscles' => ['Oblicuos', 'Flexores de cadera'],
                'benefits' => ['Enseña la estabilización anti-extensión', 'Seguro para la espalda baja', 'Mejora la coordinación contralateral'],
                'level' => 'Principiante',
            ],
            [
                'name' => 'Crunch en Polea Alta',
                'muscleGroup' => 'Core',
                'equipment' => 'Polea alta con cuerda',
                'description' => 'Arrodillado frente a la polea alta, agarra la cuerda detrás de la cabeza. Flexiona el tronco hacia abajo contrayendo el abdomen. Regresa controladamente.',
                'primaryMuscles' => ['Recto abdominal'],
                'secondaryMuscles' => ['Oblicuos'],
                'benefits' => ['Permite añadir resistencia progresiva', 'Mayor activación que el crunch tradicional', 'Ideal para hipertrofia abdominal'],
                'level' => 'Principiante',
            ],
            [
                'name' => 'Hollow Hold',
                'muscleGroup' => 'Core',
                'equipment' => 'Peso corporal',
                'description' => 'Acostado boca arriba, eleva los brazos extendidos por encima de la cabeza y las piernas rectas del suelo. Mantén la espalda baja pegada al suelo formando una C con el cuerpo.',
                'primaryMuscles' => ['Recto abdominal', 'Transverso abdominal'],
                'secondaryMuscles' => ['Flexores de cadera', 'Cuádriceps'],
                'benefits' => ['Ejercicio fundamental de gimnasia', 'Desarrolla fuerza de core profunda', 'Mejora la postura y el control corporal'],
                'level' => 'Intermedio',
            ],
        ];

        foreach ($exercises as $ex) {
            Exercise::updateOrCreate(
            ['slug' => Str::slug($ex['name'])],
            [
                'name' => $ex['name'],
                'muscle_group_id' => $muscleGroups[$ex['muscleGroup']] ?? null,
                'equipment' => $ex['equipment'],
                'description' => $ex['description'],
                'primary_muscles' => $ex['primaryMuscles'],
                'secondary_muscles' => $ex['secondaryMuscles'],
                'benefits' => $ex['benefits'],
                'level' => $ex['level'],
                'is_custom' => false,
            ]
            );
        }
    }
}
